Delete animation on stop
MissionToPsyche/tungsten_01b_ar_xr-psb pull request #43
Opened 2024-01-24 15:29 UTC by azigerelli

Adds functionality to the `AnimationProvider` so that animations are deleted after they are stopped. Also found and fixed another bug. I noticed if an animation was active and you click the restart button and then cycle through the scenes back to where you were, the animation would start as soon the scene loaded. I added a function to clear all animations from the registry and call that any time restart is pressed.

2024-01-24 16:08 UTC, ajd6735 approved these changes

2024-01-24 16:27 UTC, zlix12 reviewed
Looks good logically. Will approve after merge conflicts are resolved.

2024-01-28 17:10 UTC, zlix12 requested changes

2024-01-28 17:10 UTC, zlix12 commented on src/artifacts/Orbiter.tsx
Can we reset this file to main version?

2024-01-30 02:15 UTC, zlix12 approved these changes
LGTM

2024-01-30 02:16 UTC, merged