Add first scene dates
MissionToPsyche/tungsten_01b_ar_xr-psb pull request #44
Opened 2024-01-26 16:44 UTC by ajd6735

In this commit, I incorporated animated date objects, added facts modal to each, and adjusted the mission-facts-test file to ensure facts are now under 100 characters. It's worth noting that our documentation specifies the content should be less than 60 words for each fact, not 60 characters.

2024-01-28 18:34 UTC, zlix12 requested changes
Looks good visually, just a few fixes needed.

2024-01-28 18:34 UTC, zlix12 commented on src/scene/scenes/AssemblyScene.tsx
> +    <ModelOutliner color={0xffffff}>
`SceneManager` already wraps all of the in a `ModelOutliner` so you should not need it here.

2024-01-28 18:34 UTC, zlix12 commented on src/artifacts/AssembTestDates.tsx
Seems like this is not used?

2024-01-29 05:28 UTC, ajd6735 commented on src/artifacts/AssembTestDates.tsx
I admire your attention to detail, yes you are correct, this file is unnecessary.

2024-01-29 18:25 UTC, zlix12 approved these changes
LGTM

2024-01-30 03:15 UTC, merged