Add assembly scene
MissionToPsyche/tungsten_01b_ar_xr-psb pull request #96
Opened 2024-03-13 04:13 UTC by ajd6735

Adds a new assembly scene and modifies the order of the assembly scenes

2024-03-17 15:59 UTC, zlix12 submitted a review, later dismissed
Looks great

2024-03-18 03:05 UTC, AvinaashGhansam submitted a review, later dismissed

2024-03-18 04:05 UTC, zlix12 requested changes
Looks good just one small thing noted

2024-03-18 04:05 UTC, zlix12 commented on src/scene/get-scene-config.ts
> +        // animation: AnimationName.BACK,
Should this be un-commented?

2024-03-18 04:17 UTC, zlix12 approved these changes
LGTM

2024-03-18 04:18 UTC, merged